# Generated by Django 2.0.5 on 2018-05-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortName', models.CharField(max_length=200)),
                ('iupacName', models.CharField(max_length=200)),
                ('molecularFormula', models.CharField(max_length=200)),
                ('structure', models.CharField(max_length=200)),
                ('cid', models.CharField(max_length=200)),
            ],
        ),
    ]
