# Generated by Django 2.0.5 on 2018-05-25 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortName', models.CharField(max_length=200, unique=True)),
                ('iupacName', models.CharField(max_length=1200, unique=True)),
                ('molecularFormula', models.CharField(max_length=1200, unique=True)),
                ('structure', models.CharField(max_length=10000, unique=True)),
                ('cid', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiptDate', models.DateField()),
                ('storageLife', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=20)),
                ('measurementUnits', models.IntegerField(verbose_name=((1, 'mg'), (2, 'kg'), (3, 'g'), (4, 'ml'), (5, 'l'), (6, 'nl')))),
                ('comments', models.CharField(max_length=200)),
                ('compoundId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitallab.Compound')),
            ],
        ),
        migrations.CreateModel(
            name='ReagentLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=1200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='reagent',
            name='reagentLocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitallab.ReagentLocation'),
        ),
    ]
