# Generated by Django 2.0.5 on 2018-05-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitallab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiptDate', models.DateField()),
                ('storageLife', models.CharField(max_length=200)),
                ('compoundId', models.IntegerField()),
                ('amount', models.CharField(max_length=200)),
                ('reagentLocation', models.IntegerField()),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReagentLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=200)),
            ],
        ),
    ]
